<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <PackageId>Almostengr.FalconPiPlayer.ApiClient</PackageId>
    <Company>Robinson Handy and Technology Services LLC</Company>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(yyyy)) Robinson Handy and Technology Services</Copyright>
    <Product>Almostengr FalconPiPlayer API Client Library</Product>
    <Authors>Kenny Robinson</Authors>
    <AssemblyName>Almostengr.FalconPiPlayer.ApiClient</AssemblyName>
    <RootNamespace>Almostengr.FalconPiPlayer.ApiClient</RootNamespace>
    <Version>10.$([System.DateTime]::UtcNow.ToString(yyyy.MM.ddHH))</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/almostengr/falcon-pi-player-apiclient.git</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Almostengr.Common" Version="10.2026.718.2325" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.12" />
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
